version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres-export_trace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: export_trace_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d   # <--- Monta tus scripts de inicialización

volumes:
  pgdata:
