// <auto-generated />
using System;
using Export_trace_module.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Export_trace_module.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250525085117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Export_trace_module.Models.ConsultaAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.ToTable("ConsultasAPI");
                });

            modelBuilder.Entity("Export_trace_module.Models.DatosAExportar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaAPIId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<int?>("CultivoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaExportacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("PlagaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaAPIId");

                    b.HasIndex("FechaExportacion");

                    b.HasIndex("TipoDato");

                    b.ToTable("DatosAExportar");
                });

            modelBuilder.Entity("Export_trace_module.Models.Plaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaAPIId")
                        .HasColumnType("integer");

                    b.Property<int>("CultivoId")
                        .HasColumnType("integer");

                    b.Property<string>("CultivoNombre")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DetectadaPorPrimeraVez")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("EsEndemica")
                        .HasColumnType("boolean");

                    b.Property<string>("Fuente")
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("text");

                    b.Property<string>("Sintomas")
                        .HasColumnType("text");

                    b.Property<string>("TipoPlaga")
                        .HasColumnType("text");

                    b.Property<string>("TratamientoRecomendado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaAPIId");

                    b.ToTable("Plaga");
                });

            modelBuilder.Entity("Export_trace_module.Models.DatosAExportar", b =>
                {
                    b.HasOne("Export_trace_module.Models.ConsultaAPI", "ConsultaAPI")
                        .WithMany("DatosExportados")
                        .HasForeignKey("ConsultaAPIId");

                    b.Navigation("ConsultaAPI");
                });

            modelBuilder.Entity("Export_trace_module.Models.Plaga", b =>
                {
                    b.HasOne("Export_trace_module.Models.ConsultaAPI", null)
                        .WithMany("Plagas")
                        .HasForeignKey("ConsultaAPIId");
                });

            modelBuilder.Entity("Export_trace_module.Models.ConsultaAPI", b =>
                {
                    b.Navigation("DatosExportados");

                    b.Navigation("Plagas");
                });
#pragma warning restore 612, 618
        }
    }
}
