// <auto-generated />
using System;
using ExportModule.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExportModule.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608154407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExportModule.Models.ConsultaAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ConsultaAPIs");
                });

            modelBuilder.Entity("ExportModule.Models.Cultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("ExportModule.Models.DatosAExportar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaAPIId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<int?>("CultivoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaExportacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formato")
                        .HasColumnType("text");

                    b.Property<int?>("PlagaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDato")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaAPIId");

                    b.HasIndex("CultivoId");

                    b.HasIndex("PlagaId");

                    b.ToTable("DatosAExportar");
                });

            modelBuilder.Entity("ExportModule.Models.Plaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaAPIId")
                        .HasColumnType("integer");

                    b.Property<int>("CultivoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaAPIId");

                    b.HasIndex("CultivoId");

                    b.ToTable("Plagas");
                });

            modelBuilder.Entity("ExportModule.Models.TareaProgramada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoIntento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TareasProgramadas");
                });

            modelBuilder.Entity("ExportModule.Models.DatosAExportar", b =>
                {
                    b.HasOne("ExportModule.Models.ConsultaAPI", "ConsultaAPI")
                        .WithMany("DatosAExportar")
                        .HasForeignKey("ConsultaAPIId");

                    b.HasOne("ExportModule.Models.Cultivo", "Cultivo")
                        .WithMany("DatosAExportar")
                        .HasForeignKey("CultivoId");

                    b.HasOne("ExportModule.Models.Plaga", "Plaga")
                        .WithMany("DatosAExportar")
                        .HasForeignKey("PlagaId");

                    b.Navigation("ConsultaAPI");

                    b.Navigation("Cultivo");

                    b.Navigation("Plaga");
                });

            modelBuilder.Entity("ExportModule.Models.Plaga", b =>
                {
                    b.HasOne("ExportModule.Models.ConsultaAPI", "ConsultaAPI")
                        .WithMany("Plagas")
                        .HasForeignKey("ConsultaAPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportModule.Models.Cultivo", "Cultivo")
                        .WithMany("Plagas")
                        .HasForeignKey("CultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaAPI");

                    b.Navigation("Cultivo");
                });

            modelBuilder.Entity("ExportModule.Models.ConsultaAPI", b =>
                {
                    b.Navigation("DatosAExportar");

                    b.Navigation("Plagas");
                });

            modelBuilder.Entity("ExportModule.Models.Cultivo", b =>
                {
                    b.Navigation("DatosAExportar");

                    b.Navigation("Plagas");
                });

            modelBuilder.Entity("ExportModule.Models.Plaga", b =>
                {
                    b.Navigation("DatosAExportar");
                });
#pragma warning restore 612, 618
        }
    }
}
